apiVersion: v1
kind: Secret
metadata:
  name: config-service-secret
  namespace: dev
type: Opaque
data:
  # Add your secret environment variables here in base64
  # Example:
  # CONFIG_ENCRYPTION_KEY: eW91cl9jb25maWdfZW5jcnlwdGlvbl9rZXk=  # your_config_encryption_key in base64
